package Crypt

import (
	"AllSecure/ListeningServer/Common"
	"crypto/aes"
	"crypto/cipher"
	"log"
)

// .\PayloadDecryptor.exe <base64 encoded encrypted payload> <size of encrypted payload> <b64 AESKey> <SizeofAESKey> <b64 IV> <SizeOf IV>
// TODO: Offshore this work to a binary that uses the tomcrypt library since go does not inherently support AES CTR without fucking up the cipher text generated by tomcrypt.
func AESDecryptPayload(DataPackage Common.Package, filepath string) ([]byte, error) {
	var (
		err             error
		DecryptedAESKey []byte
		DecryptedIV     []byte
	)

	DecryptedAESKey, err = DecryptKeyIV(DataPackage.EncryptedAESKey, filepath)
	if err != nil {
		return []byte{}, err
	}

	DecryptedIV, err = DecryptKeyIV(DataPackage.EncryptedIV, filepath)
	if err != nil {
		return []byte{}, err
	}

	block, err := aes.NewCipher(DecryptedAESKey)
	if err != nil {
		log.Println("[error] attempting to create new aes block", err)
		return []byte{}, err
	}
	stream := cipher.NewCTR(block, DecryptedIV)
	plaintext := make([]byte, DataPackage.EncryptedDataSize)
	stream.XORKeyStream(plaintext, DataPackage.EncryptedData)

	return plaintext, nil

}
